### ISSUE TITLE
How to install ?!

### ISSUE THREAD

**Issue by mtsmayad** [kistolbov/make-your-own-url-shortener#1]
Hi,

I want this url shortener can u help me run it on a web host, or just download upload and that is it :)

Regards,

**Comment by kistolbov** [comment]
To be honest, I didn't finish it. I'll write when it will be ready before the end.4:50 PM, February 1, 2020, mtsmayad <notifications@github.com>:Hi,
I want this url shortener can u help me run it on a web host, or just download upload and that is it :)
Regards,

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Sent from Yandex.Mail for mobile

**Comment by mtsmayad** [comment]
Thank u, I will watch u finishing it...
My u suggest me a way to learn how to program my own url shortener, the easy way, I have no information of programming at all ?!
Regards,

**Comment by kistolbov** [comment]
I uploaded a last verson. Just clone it and write:
$ python manage.py migrate
$ python managee.ru runserver
